# 1. Seção exclusiva para o Banco de Dados
databases:
  - name: invest-bot-db
    databaseName: bot_db
    user: postgres
    plan: free

services:
  # 2. Redis (Fica dentro de services)
  - type: redis
    name: invest-bot-redis
    plan: free
    ipAllowList: []

  # 3. Evolution API
  - type: web
    name: evolution-api
    env: docker
    plan: free
    envVars:
      - key: DATABASE_ENABLED
        value: "true"
      - key: DATABASE_CONNECTION_URI
        fromDatabase:
          name: invest-bot-db
          property: connectionString
      - key: REDIS_ENABLED
        value: "true"
      - key: REDIS_HOST
        fromRedis:
          name: invest-bot-redis
          property: host
      - key: REDIS_PORT
        fromRedis:
          name: invest-bot-redis
          property: port
      - key: AUTHENTICATION_API_KEY
        value: "4f7b2e9d1a8c6b5e0f9d2a3c4b5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3"

  # 4. Seu Bot Python
  - type: web
    name: python-invest-bot
    env: docker
    rootDir: bot
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: EVO_URL
        value: https://evolution-api.onrender.com # Ajuste após o deploy
      - key: EVO_API_KEY
        value: "4f7b2e9d1a8c6b5e0f9d2a3c4b5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3"
      - key: INSTANCE_NAME
        value: "InvestBot"
      - key: VALOR_APORTE
        value: "185.00"
